---
title: "Midterm Memo"
subtitle: "Independent Study 399" 
author: "Kayla Terrelonge"

format:
  html:
    toc: true
    self-contained: true

reference-location: margin

execute:
  warning: false
  message: false
---
::: {.callout-note}
[Github Repo Link](https://github.com/kaylaterrelonge/thesis-project-final)
:::

## Overview 

For my thesis project, I am looking to uncover if the widespread legalization of Sports Betting has had an impact on player performance in Major League Baseball. I aim to understand if the potential relationship is due to a boost in morale, loyalty to fans, or other unknown reasons.

## What Has Been Done

The first weeks of the quarter were spent on data collection. The original source of my dataset was ESPN, however, because they utilize user-interactive features it made web scraping nearly impossible. Thus, I decided to search for a new data source, the MLB website, and web scrape through the use of for loops. From there, I spent the next few weeks writing a function to clean the data, as it was extremely messy and unreadable after the initial web scraping process. I began some preliminary EDA work, which was aided with scholarly research on sports betting legalization in the United States. This EDA work was then used to limit the scope of the data set to a particular time frame and to see if there are patterns that align with the hypothesis of my research.

## Where Are We Now?

As of now, I have narrowed down the variables I would like to use to investigate this trend (Batting Averages, Runs Batted In, and On Base Plus Slugging). I have reduced the data set to a time frame that will best aid in answering the question of this research. I have conducted unidirectional hypothesis testing to confirm statistical significance. Now, I have seen that there is an increase in player performance in the seasons between sports betting being legalized.

## Where Is This Leading?

The next steps of this project is to perform feature selection and begin a forecast modeling to predict how sports betting becoming an integral part of sports entertainment will affect player performance. From there, based on data availability, some other future steps would involve predicting how much revenue would be generated from betting from a particular team, given their performance.